# -*- coding: utf-8 -*-
# :Project:   python-rapidjson -- Configuration to build and upload manylinux1 wheels to PyPI
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   MIT License
# :Copyright: © 2017 Lele Gaifax
#

# Note that due to a strange issue with Travis CI, the Python 3.6 wheels are
# actually built via Gitlab CI, on the repository
# https://gitlab.com/metapensiero/python-rapidjson.
#
# Here we execute the Python 3.6 tests; Python 3.4 and 3.5 tests are run by
# cibuildwheel, inside the manylinux1 Docker image.
#
# See https://mail.python.org/pipermail/wheel-builders/2017-August/000285.html

matrix:
  include:
    - sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - os: osx
      osx_image: xcode8.3

env:
  global:
    - CIBW_TEST_REQUIRES="pytest pytest-benchmark pytz"
    - CIBW_TEST_COMMAND="py.test {project}/tests"
    - CIBW_SKIP="cp2* cp33* cp36*"
    - TWINE_USERNAME=lelit
      # Note: TWINE_PASSWORD is set in Travis settings

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install python3; fi
  - pip3 install -r requirements-test.txt

script:
  - pip3 install . && pytest tests
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      pip3 install cibuildwheel==0.5.0
      cibuildwheel --output-dir wheelhouse
      if [[ $TRAVIS_TAG ]]; then
        pip install twine
        twine upload wheelhouse/*.whl
      fi
    fi
