matrix:
  include:
    - sudo: required
      services:
        - docker
#    - os: osx
#      language: generic
#      env:
#        - PY_VERSION=3

env:
  global:
    - CIBW_TEST_REQUIRES="pytest pytest-benchmark pytz"
    - CIBW_TEST_COMMAND="py.test {project}/tests"
    - CIBW_SKIP="cp2* cp33*"
    - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy
    - TWINE_USERNAME=lelit
      # Note: TWINE_PASSWORD is set in Travis settings

language: python
python: "3.5"

script:
  - python3 -m pip install https://github.com/tgarc/cibuildwheel/archive/master.zip
  - python3 -m cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
