# -*- coding: utf-8 -*-
# :Project:   python-rapidjson -- Appveyor configuration to build and upload manylinux1 wheels to PyPI
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   MIT License
# :Copyright: © 2017 Lele Gaifax
#

language: python
python: "3.6"

matrix:
  include:
    - sudo: required
      services:
        - docker
#    - os: osx
#      language: generic
#      env:
#        - PY_VERSION=3

env:
  global:
    - CIBW_TEST_REQUIRES="pytest pytest-benchmark pytz"
    - CIBW_TEST_COMMAND="py.test {project}/tests"
    - CIBW_SKIP="cp2* cp33*"
    - TWINE_USERNAME=lelit
      # Note: TWINE_PASSWORD is set in Travis settings

install: pip install -r requirements-test.txt

script:
  - pip install cibuildwheel==0.4.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      pip install twine
      twine upload wheelhouse/*.whl
    fi
